name: Deploy VPS

on:
  push:
    branches:
      - main
      - master

  schedule:
    - cron: "0 9,21 * * *"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy no VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /root/lavagem_novo
            git pull
            pip3 install -r requirements.txt
            systemctl restart lavagem
